### ISSUE TITLE
OpenSearch Client

### ISSUE THREAD

**Issue by sboeckelmann** [reactiverse/reactiverse#17]
Elasticsearch and OpenSearch are moving more and more apart with each release. 
To have better support for OpenSearch clusters, I want to suggest to also create an opensearch-client project based on the existing elasticsearch-client. 
I was working on a simple proof-of-concept project that showed that the existing shims can easily adjusted to the latest OpenSearch 2.4.1 as well.
I would also volunteer to maintain the new opensearch-client reactive client.

**Comment by tsegismont** [comment]
Hi @sboeckelmann , thank you for starting this conversation.

It is important that a [new project proposal](https://github.com/reactiverse/reactiverse/blob/master/Governance.adoc#project-proposal) comes with some poc that we can take a look at.

If you have started this, can you share a link to the corresponding GitHub repo ?

**Comment by sboeckelmann** [comment]
> If you have started this, can you share a link to the corresponding GitHub repo ?

Sorry, should have shared it right away. 
https://github.com/sboeckelmann/reactiverse-opensearch-client

**Comment by tsegismont** [comment]
So it seems there is no fundamental difference so far between this project and the Elasticsearch client project.

I guess so far you've been using the Elasticsearch client JAR with Opensearch, right? What is it which is not well supported in this case?

**Comment by loicmathieu** [comment]
@tsegismont due to licence change at Elasticsearch side, the current High Level client is blocked to an old version.
New versions are not compatible with OpenSearch and the two projets starts to diverge.

At Elasticsearch side, there is a new Java Client that will replace the high level client. 
At Quarkus side, we will drop support for the current High Level client in favor of the new Java Client, but this will means OpenSearch will not be supported anymore.

So this client that has been created for integration into Quarkus https://github.com/reactiverse/elasticsearch-client should be deprecated one day or another in favor of the elasticsearch Java client https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/current/index.html and an OpenSearch client.

**Comment by sboeckelmann** [comment]
https://opensearch.org/docs/latest/clients/java-rest-high-level/#elasticsearch-oss-java-high-level-rest-client

**Comment by tsegismont** [comment]
> So this client that has been created for integration into Quarkus https://github.com/reactiverse/elasticsearch-client should be deprecated one day or another in favor of the elasticsearch Java client

@loicmathieu are you sure the link is correct? The Reactiverse Elasticsearch client has not bren created for integration into Quarkus afaik

**Comment by loicmathieu** [comment]
@tsegismont you're right, it's the Mutiny variant that has been created for Quarkus.
https://github.com/reactiverse/elasticsearch-client/tree/master/elasticsearch-client-mutiny

**Comment by loicmathieu** [comment]
And if you look at its versions, it still uses an old, open source version of the client https://github.com/reactiverse/elasticsearch-client/blob/master/build.gradle.kts#L34 that is still compatible with both Elasticsearch and OpenSearch.

**Comment by tsegismont** [comment]
Thank you both for clarifications.

> deprecated one day or another in favor of the elasticsearch Java client https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/current/index.html and an OpenSearch client.

This issue has been filed to propose a reactive client based on Opensearch high-level REST Client.
What's the future of the Opensearch high-level REST Client? Is it going to disappear? From the previous comments it seems the Elastic one is going to.

**Comment by sboeckelmann** [comment]
I am not aware of any plans to deprecate the OpenSearch high-level REST client.
But if that's going to the case, that shouldn't be much of an issue - we could just integrate the new client as another submodule.
By having separate reactiverse projects for Elasticsearch and OpenSearch we have all the freedom and options to address any changes that might come up in the future. 
And that's also the main reason for this proposal: OpenSearch and Elasticsearch are simply drifting apart.

**Comment by jponge** [comment]
### On Elasticsearch support

My understanding is that Elastic is making a new Java client that is properly opensource. Perhaps @swallez can give inputs? (sorry Sylvain if you are not the right contact).

If there's a new client with nice async support then it'd be good to study how to leverage it in a Vert.x context.

### On OpenSearch Vert.x reactive client

It would be great to support it, and if it's easy to do so by forking the generator that I had initially contributed please do so 👍

**Comment by sboeckelmann** [comment]
> ### On OpenSearch Vert.x reactive client
> It would be great to support it, and if it's easy to do so by forking the generator that I had initially contributed please do so 👍

Thanks! OpenSearch 2.4 has some nice new features and is very poorly supported when using the old 7.10.2 elasticsearch client. Looking forward to have official OpenSearch reactive client support!

**Comment by tsegismont** [comment]
Ok, thank you both.

@sboeckelmann in your project, it seems the integration test module is still depending on the Elasticsearch test container.
Can you please update the module so that tests run against an Opensearch server?

**Comment by tsegismont** [comment]
@jponge I believe we can start a vote after the tests have been updated and the suite passes. Or am I missing something?

**Comment by swallez** [comment]
@jponge indeed, there's a [new Java client for Elasticsearch](https://github.com/elastic/elasticsearch-java/). Its first GA release was in late 2021 😉 

The main changes compared to the older High-Level Rest Client:
- minimal dependencies: it doesn't depend on the Elasticsearch server, and only needs Apache HttpClient and a JSON Parser (Jackson or JSON-P at the moment)
- async client that returns a `CompletableFuture` instead of custom callbacks
- fully Apache-2 licensed (no use of an exception to the Elastic License for usage in a client application)
- offers classic builders and a fluent DSL based on lambda expressions.

It requires Elasticsearch 7.14 or more and will not work with OpenSearch though.

**Comment by sboeckelmann** [comment]
> I believe we can start a vote after the tests have been updated and the suite passes. Or am I missing something?

Ok, I will update the tests asap and let you now

**Comment by loicmathieu** [comment]
@jponge @swallez for Quarkus, the new Java Client will be supported for Quarkus 3 at it needs Jakarta EE. The on-ice PR is here: https://github.com/quarkusio/quarkus/pull/22622

I planned to ask for a reactiverse Vert.x client for it later so we can have a reactive extension for the Elasticsearch java client after the sync client would be integrated into Quarkus. 

@jponge you can start to work on a reactive version of the Java client at Vert.x side so. It would allow me to deprecate the current Elasticsearch reactive extension based on the high level client that we don't want to support anymore (https://github.com/quarkiverse/quarkus-elasticsearch-reactive).

**Comment by swallez** [comment]
@loicmathieu thanks for the pointer. I had a quick look and I can certainly help on some of the issues reported there.

I also said that the new Elasticsearch Java client is async and based on `CompletableFuture`. Would it help Vert.x and Quarkus if we also provided a reactive version? The code is generated so this isn't a huge effort. Our baseline is still Java 8 though, so this would be either a separate artifact or a multi-release JAR.

**Comment by jponge** [comment]
> @jponge I believe we can start a vote after the tests have been updated and the suite passes. Or am I missing something?

Yes we can start a vote after that to stamp the project creation

**Comment by jponge** [comment]
> @jponge you can start to work on a reactive version of the Java client at Vert.x side so. It would allow me to deprecate the current Elasticsearch reactive extension based on the high level client that we don't want to support anymore (https://github.com/quarkiverse/quarkus-elasticsearch-reactive).

I don't have the bandwidth to work on that at the moment

**Comment by jponge** [comment]
> @loicmathieu thanks for the pointer. I had a quick look and I can certainly help on some of the issues reported there.
> 
> I also said that the new Elasticsearch Java client is async and based on `CompletableFuture`. Would it help Vert.x and Quarkus if we also provided a reactive version? The code is generated so this isn't a huge effort. Our baseline is still Java 8 though, so this would be either a separate artifact or a multi-release JAR.

If the async API provides custom callbacks and `CompletableFuture` then bridging to Vert.x `Future` or Mutiny `Uni` is doable through code generation.

@swallez What exactly do you mean by

> Would it help Vert.x and Quarkus if we also provided a reactive version?

Doing the Vert.x client library on your side?

**Comment by jponge** [comment]
Just to be sure @sboeckelmann: are you ready to contribute and maintain an OpenSearch client?

Always better to ask 😄

**Comment by sboeckelmann** [comment]
> Just to be sure @sboeckelmann: are you ready to contribute and maintain an OpenSearch client?

Yes, of course! - scroll all the way up to my very first message 😃 

I just finished adjusting the unit tests, and they are passing just fine:
https://github.com/sboeckelmann/reactiverse-opensearch-client/actions

Deployment is of course currently disabled but I already prepared the gradle deployment descriptors for a future reaciverse/opensearch-client repo.

**Comment by sboeckelmann** [comment]
sorry, only build is running with ci-cd - https://github.com/sboeckelmann/reactiverse-opensearch-client/actions
will adjust action and add the tests

**Comment by sboeckelmann** [comment]
Apart from the REST high-level client there's also a java-client implementation available for OpenSearch:
https://opensearch.org/docs/2.4/clients/java/
I will try to make this one reactive also, but let's get started with the REST high-level first. Not everyone has migrated their applications to use the more recent java-client.
But in order to have future support it, I would suggest to rename the opensearch-client-[rxjava2,rxjava3,mutiny] artifacts to opensearch-rest-high-level-cient-[rxjava2,rxjava3,mutiny].
The new reactive opensearch-java client can then be named opensearch-java-client-[rxjava2,rxjava3,mutiny]

I know, these are pretty long artifacts names. If you have a better idea, please shoot! But this way it's clear which opensearch client is used underneath.

**Comment by jponge** [comment]
> I know, these are pretty long artifacts names. If you have a better idea, please shoot! But this way it's clear which opensearch client is used underneath.

Better be explicit 👍

**Comment by tsegismont** [comment]
> I just finished adjusting the unit tests, and they are passing just fine:
> https://github.com/sboeckelmann/reactiverse-opensearch-client/actions

@sboeckelmann thank you
@jponge ready for vote?

**Comment by jponge** [comment]
Yes you can start it

**Comment by swallez** [comment]
@jponge 

> @swallez What exactly do you mean by
>
> >   Would it help Vert.x and Quarkus if we also provided a reactive version?
>
> Doing the Vert.x client library on your side?

I was thinking of a variant of the Elasticsearch client whose methods would return `Flow.Publisher` instead of `CompletableFuture`, and not about introducing dependencies on a specific implementation of reactive streams.

Now since these publishers would produce a single value, maybe they don't have much added value compared to using the implementation-specific `Mono.fromFuture()` or `Uni.createFrom().completionStage()`, as we would end up using these classes anyway since they provide additional behavior based on the fact that a single value is produced. WDYT?

**Comment by swallez** [comment]
@sboeckelmann 

> Apart from the REST high-level client there's also a java-client implementation available for OpenSearch:
https://opensearch.org/docs/2.4/clients/java/

FWIW this is a fork of an alpha version of [Elastic's new Java client](https://github.com/elastic/elasticsearch-java/) that has been barely updated since then.

**Comment by sboeckelmann** [comment]
> FWIW this is a fork of an alpha version of [Elastic's new Java client](https://github.com/elastic/elasticsearch-java/) that has been barely updated since then.

Yes, I know - we will see how things with the new Apache 2.0 versioned Elasticsearch client will evolve and into which direction OpenSearch is going.

**Comment by jponge** [comment]
> I was thinking of a variant of the Elasticsearch client whose methods would return `Flow.Publisher` instead of `CompletableFuture`, and not about introducing dependencies on a specific implementation of reactive streams.
> 
> Now since these publishers would produce a single value, maybe they don't have much added value compared to using the implementation-specific `Mono.fromFuture()` or `Uni.createFrom().completionStage()`, as we would end up using these classes anyway since they provide additional behavior based on the fact that a single value is produced. WDYT?

That's interesting.

I agree that if there's always 1 value to be produced you should stick to `CompletionStage`, this is the proper JDK-provided abstraction for 1-shot asynchronous events.

Otherwise if there are places with _streams_ you might be interested by the low-overhead Mutiny Zero library to build _correct_ `Flow.Publisher`: https://smallrye.io/smallrye-mutiny-zero/1.0.0/quick-start/

**Comment by swallez** [comment]
> I agree that if there's always 1 value to be produced you should stick to CompletionStage, this is the proper JDK-provided abstraction for 1-shot asynchronous events.

Indeed. So let's forget about `Flow.Publisher` for this.

> Otherwise if there are places with streams you might be interested by the low-overhead Mutiny Zero library to build correct Flow.Publisher: https://smallrye.io/smallrye-mutiny-zero/1.0.0/quick-start/

Absolutely, there are a few APIs where multivalue publishers (e.g. pagination, point-in-time) and consumers (e.g. bulk ingestion) definitely make sense. I didn't know about Mutiny Zero, thanks for the link!

**Comment by michael-simons** [comment]
👀 TIL Mutiny Zero

**Comment by tsegismont** [comment]
@reactiverse/maintainers please cast your vote

Here's my :+1:

**Comment by jponge** [comment]
I also applaud the effort so 👍

**Comment by tsegismont** [comment]
Please cast your vote @reactiverse/maintainers

**Comment by tsegismont** [comment]
cc @aesteve @cescoffier @elR1co @FroMage @pmlopes @romalev @slinkydeveloper @vietj

**Comment by pmlopes** [comment]
:+1:

**Comment by cescoffier** [comment]
👍

**Comment by vietj** [comment]
my +1

**Comment by tsegismont** [comment]
We have a quorum.

@sboeckelmann I'll come back to you shortly.

**Comment by slinkydeveloper** [comment]
:+1:

**Comment by romalev** [comment]
:+1:

**Comment by tsegismont** [comment]
Thanks everyone for casting your vote.

@sboeckelmann I've sent an invite to you for becoming a member of the reactiverse org. Please accept it and then transfer your repository to the org. If it doesn't work, I'll create a new repo.

**Comment by tsegismont** [comment]
Congrats @sboeckelmann and welcome to the Reactiverse ;-)

**Comment by sboeckelmann** [comment]
🎉  Thank you everyone!

**Comment by sboeckelmann** [comment]
just be sure: 
next step for me would be to create the opensearch-cient repository right here on reactiverse and get it going, right?

**Comment by tsegismont** [comment]
Instead of creating a new repo, you could transfer your existing repo to this org.

**Comment by tsegismont** [comment]
Well done @sboeckelmann . Can you please create an issue in the new repo with a list of tasks before the first release? We should have least have docs, CI and release process. Given you're starting from the Reactiverse Elasticsearch client base, a lot of the problems are already solved I guess.

**Comment by sboeckelmann** [comment]
Dear @tsegismont 
I have created https://github.com/reactiverse/opensearch-client/issues/4 to track first release.
Currently I am struggling with signing for deployments. Tried to use secrets env names used by other projects on reactiverse.
Can you please help me to setup GPG signing key from organization?

**Comment by tsegismont** [comment]
@jponge @vietj can one of you please help @sboeckelmann while I'm out of office? Thanks

**Comment by jponge** [comment]
I don't have the credentials, I think @vietj does

**Comment by vietj** [comment]
for GPG : you need to sign the release with your GPG key that should be added to a white list, details are provided in sonatype guide

**Comment by sboeckelmann** [comment]
I don't have access to the settings to resolve https://github.com/reactiverse/opensearch-client/issues/4. Don't want to share my gpg private in the repo and would like to setup secrets using the project's settings.

@vietj , @tsegismont anyone who can setup the required rights for me?

**Comment by aesteve** [comment]
This is (and always has been) a big blocker for [the AWS SDK](https://github.com/reactiverse/aws-sdk) as well.

Can we sort this out once and for all for every reactiverse project?

For example setting up GPG credentials at the organisation level so that every project can just use those in the appropriate Github Action?

I know the workaround is (and always has been) "publish releases from your machine" but that's really not a satisfying solution for me.

I'm happy to discuss this this week if you want @vietj but since we moved out of Bintray for the release process I've been struggling with this and only published Snapshots for the same reason as @sboeckelmann .

Users are waiting for this: https://github.com/reactiverse/aws-sdk/issues/57#issuecomment-1457016676

**Comment by tsegismont** [comment]
@sboeckelmann @aesteve I'm not a PGP expert but why not creating a separate key for your work in the Reactiverse? It's not required to use the key that you may use for signing your commits or your emails, for example.

**Comment by aesteve** [comment]
That’s what I did to unlock the situation and perform a release but still
the key is linked to my email address.

Meaning I’ll have to not forget to delete/invalidate it if handing the
project over for example.

That’s not ideal 😔

If we have more & more projects in the reactiverse org, and want to push in
favor of individual contributors to take ownership of those, providing
everything necessary to lower the necessary steps to perform releases would
be good imo.

A set of signing keys bound to a generic ***@***.*** address
for instance, set at org level secrets in Github would allow any new
contributor to copy the CD Github actions from another Reactiverse project
in no time.

Note that even after that the process to perform the release isn’t
straightforward since you have to login in Nexus and close/release…

Really, the more steps we can remove, the better

Le ven. 17 mars 2023 à 19:02, Thomas Segismont ***@***.***> a
écrit :

**Comment by patpatpat123** [comment]
Upvoting this!

**Comment by sboeckelmann** [comment]
I don't know if this is the way to go, but maybe someone who is eligible can allow me access by commenting on this ticket:
https://issues.sonatype.org/browse/OSSRH-89906
It's a request for allow my account to publish artifacts for the io.reactiverse group.

Nevertheless: We should come up with the github driven deployment for publishing artifacts. I would love to help out, but currently I am missing the required access rights to get it going.

Thank you everyone for your support!

**Comment by tsegismont** [comment]
Done @sboeckelmann
